services:

  myaiku-bot:

    build: .

    container_name: myaiku-bot

    restart: unless-stopped

    env_file:
      - .env

    environment:
      TZ: Asia/Jakarta

    volumes:
      - ./logs:/app/logs

    networks:
      - homeserver-net

networks:

  homeserver-net:
    external: true